### ISSUE TITLE
Clicking on play button in the beginning gives an error in the console. "Failed to load resource......"

### ISSUE THREAD

**Issue by nishihere19** [nishihere19/bubble_game-SOP#1]

**Comment by roottool** [comment]
The reason of this bug is the below code.
https://github.com/nishihere19/bubble_game-SOP/blob/9770f3a0922b7b445193ae14e210cde396958dc6/bbtask2.css#L1
Browser can't load `compass/css3`.

So we have two solution of it.

1. Remove this code.
2. Use https://github.com/Igosuki/compass-mixins.

I recommend referring to https://github.com/scout-app/scout-app/issues/408#issuecomment-518438993 if you choose the second solution.

**Comment by nishihere19** [comment]
Thanks
